"""Birleşik AIXM 5.2 dosyasını akış modunda yazar.

Girdi feature'ları zaten geçerli AIXM'dir (1. aşama üreticileri XSD'ye karşı
doğrulanmış dosyalar üretti). Bu yüzden pass-through feature'lar **birebir
kopyalanır** — yeniden serileştirilip biçim/sıra hatası riskine girilmez.
Yalnızca antimeridyen bölmesinde yeni eleman üretilir.

Namespace'ler kök elemanda bir kez bildirilir; parçalardaki tekrarlanan
bildirimler temizlenir (kök zaten tanımladığı için XML geçerliliği bozulmaz).
"""

import re

from lxml import etree

from .aixm_reader import NS_AIXM, NS_GML, NS_MESSAGE, NS_XLINK

# Yalnızca kökte zaten bildirilmiş dört önek temizlenir. `ns0` gibi beklenmedik
# bir önek çıkarsa bildirimi KORUNUR — aksi halde tanımsız önek üretip dosyayı
# bozardık (bu bir kez yaşandı: yeni üretilen elemanlara nsmap verilmemişti).
_NS_DECL_RE = re.compile(r'\s+xmlns:(?:message|aixm|gml|xlink)="[^"]*"')

# Üretilen her AIXM dosyasının ilk satırındaki imza (1. aşama üreticileri de
# aynı metni yazar; oralarda `HEADER_COMMENT` sabiti olarak duruyor).
HEADER_COMMENT = "Generated by Ibosoft AIS - ais.ibosoft.net.tr"


class MergedMessageWriter:
    """`message:AIXMBasicMessage` zarfı — feature'lar geldikçe diske yazılır."""

    def __init__(self, path, message_id, header_comment=HEADER_COMMENT):
        self._fh = open(path, "w", encoding="utf-8")
        self._fh.write('<?xml version="1.0" encoding="UTF-8"?>\n')
        self._fh.write(f"<!-- {header_comment} -->\n")
        self._fh.write(
            "<message:AIXMBasicMessage\n"
            f'    xmlns:message="{NS_MESSAGE}"\n'
            f'    xmlns:aixm="{NS_AIXM}"\n'
            f'    xmlns:gml="{NS_GML}"\n'
            f'    xmlns:xlink="{NS_XLINK}"\n'
            f'    gml:id="{message_id}">\n'
        )
        self.count = 0

    def write_member(self, member):
        """`hasMember` elemanını olduğu gibi yazar (birebir kopya)."""
        text = etree.tostring(member, encoding="unicode")
        self._fh.write("  " + _NS_DECL_RE.sub("", text).strip() + "\n")
        self.count += 1

    def close(self):
        self._fh.write("</message:AIXMBasicMessage>\n")
        self._fh.close()
