"""Antimeridyeni aşan rota segmentlerini kesişim noktasından ikiye böler.

Amaç: web haritalarında segmentin dünyayı boydan boya kat eder gibi çizilmesini
önlemek. Bölme **AIXM düzeyinde** (2A) yapılır — yeni feature'lar gerçek
`gml:identifier` ve `xlink` taşır, birleşik dosya kendi içinde tutarlı kalır.

Ara nokta neden `DesignatedPoint`: `aixm:Point`, `gml:Point` substitution
group'undadır — `AbstractAIXMFeature` değildir, `message:hasMember` olarak
yazılamaz; ayrıca `PointPropertyType` noktayı satır içine gömer, paylaşılan bir
noktaya referans veremez. Tek bir paylaşılan ara nokta üretebilmek için
`DesignatedPoint` kullanılır (kullanıcı kararı): `type=OTHER`,
`designator`/`name` boş, tanımlayıcı bilgi annotation'da.

Kesişim enlemi WGS84 elipsoidi üzerinde gerçek geodesic ile hesaplanır
(kullanıcı kararı) — küresel büyük daire yaklaşımı değil.
"""

import copy
import uuid as uuid_mod

from lxml import etree
from pyproj import Geod

from .aixm_reader import (A, G, M, NS_AIXM, NS_GML, NS_MESSAGE, NS_XLINK, X,
                          local, time_slice)

GEOD = Geod(ellps="WGS84")
SRS_NAME = "urn:ogc:def:crs:EPSG::4326"

# Yeni üretilen elemanlar kökle aynı önekleri kullanmalı; aksi halde lxml
# `ns0:` üretir ve yazıcının önek temizliği tanımsız önek bırakır.
NSMAP = {"message": NS_MESSAGE, "aixm": NS_AIXM,
         "gml": NS_GML, "xlink": NS_XLINK}

POINT_NOTE = ("Automatically generated by the AIS system to display "
              "antimeridian crossings on web maps.")
SEGMENT_NOTE = ("Route segment automatically split by the AIS system at the "
                "antimeridian for display on web maps.")

# Türetilen feature'ların UUID'leri deterministik olsun diye sabit namespace
# (1. aşama üreticileriyle aynı sabit; farklı `kind` öneki kullanıldığı için
# çakışma olmaz).
UUID_NAMESPACE = uuid_mod.UUID("6f1c3b52-9d4a-5e77-b8c1-2a0e94f7d310")

# Kesişim aramasında kabul edilen boylam sapması (derece).
LON_TOLERANCE = 1e-7


def _derived_uuid(kind: str, key: str) -> str:
    return str(uuid_mod.uuid5(UUID_NAMESPACE, f"{kind}:{key}")).upper()


def crosses_antimeridian(positions) -> bool:
    """İki uç arasındaki boylam farkı 180°'yi aşıyorsa kısa yol antimeridyeni
    keser."""
    if not positions or len(positions) < 2:
        return False
    return abs(positions[-1][1] - positions[0][1]) > 180.0


def crossing_latitude(lat1, lon1, lat2, lon2):
    """WGS84 geodesic üzerinde boylamın ±180° olduğu noktanın enlemi.

    `Geod.inv()` ile azimut/mesafe alınır, ardından mesafe boyunca ikili arama
    (bisection) yapılır: boylamın işareti başlangıç ucuyla aynı kaldığı sürece
    ileri gidilir. |Δlon| > 180 olduğu için yol ±180'i tam bir kez keser,
    dolayısıyla işaret değişimi tekildir.

    Kesişim bulunamazsa (beklenmedik geometri) `None` döner — uydurma değer
    üretilmez, çağıran segmenti bölmeden bırakır.
    """
    azimuth, _, distance = GEOD.inv(lon1, lat1, lon2, lat2)
    if not distance or distance <= 0:
        return None

    start_positive = lon1 > 0
    low, high = 0.0, distance
    for _ in range(200):
        mid = (low + high) / 2.0
        lon, lat, _ = GEOD.fwd(lon1, lat1, azimuth, mid)
        if (lon > 0) == start_positive:
            low = mid
        else:
            high = mid
        if high - low < 1e-6:          # ~1 µm
            break

    lon, lat, _ = GEOD.fwd(lon1, lat1, azimuth, low)
    if abs(abs(lon) - 180.0) > 1e-4:   # ±180'e yakınsamadıysa güvenme
        return None
    return lat


def _set_gml_ids(element, old_prefix: str, new_prefix: str):
    """Klonun içindeki tüm türetilmiş `gml:id`'leri yeni önekle yeniden yazar.

    1. aşama üreticileri iç id'leri hep `<feature gml:id>` + sonek biçiminde
    ürettiği için (`_TS`, `_TP`, `_C`, `_START`, `_END`, `_RMK` …) tek bir önek
    değişimi hepsini tutarlı biçimde yeniler.
    """
    for el in element.iter():
        gid = el.get(G + "id")
        if gid and gid.startswith(old_prefix):
            el.set(G + "id", new_prefix + gid[len(old_prefix):])


def _replace_endpoint(ts, side: str, target_uuid: str):
    """Segmentin `start`/`end` ucundaki nokta referansını yenisiyle değiştirir.

    Mevcut `pointChoice_*` elemanı yerinde `pointChoice_fixDesignatedPoint`'e
    çevrilir — altı seçenek de XSD'de aynı `<choice>` konumunda olduğu için
    eleman sırası bozulmaz.
    """
    holder = ts.find(A + side)
    if holder is None:
        return False
    for point in holder.iter():
        if local(point.tag).startswith("pointChoice_"):
            point.tag = A + "pointChoice_fixDesignatedPoint"
            point.set(X + "href", "urn:uuid:" + target_uuid)
            return True
    return False


def _set_curve(ts, positions):
    """`curveExtent` posList'ini yeni koordinatlarla yazar (enlem boylam)."""
    pl = ts.find(".//" + G + "posList")
    if pl is None:
        return False
    pl.text = " ".join(f"{lat} {lon}" for lat, lon in positions)
    return True


def _add_note(ts, gml_id: str, text: str, suffix: str):
    """`annotation` → `Note` ekler.

    Mevcut annotation'lar korunur; bu ek bir `annotation`'dır (AIXM'de 0..∞).
    XSD sırası gereği `annotation`, RouteSegment'te `end`'den sonra gelir —
    bu yüzden sona eklenir.
    """
    ann = etree.SubElement(ts, A + "annotation")
    note = etree.SubElement(ann, A + "Note")
    note.set(G + "id", f"{gml_id}_{suffix}")
    etree.SubElement(note, A + "purpose").text = "REMARK"
    translated = etree.SubElement(note, A + "translatedNote")
    ling = etree.SubElement(translated, A + "LinguisticNote")
    ling.set(G + "id", f"{gml_id}_{suffix}_LN")
    etree.SubElement(ling, A + "note").text = text


def _build_crossing_point(gml_id, point_uuid, lat, lon, valid_time_source):
    """Ara nokta için `DesignatedPoint` feature'ı (`hasMember` sarmalı ile).

    XSD sırası: designator, type, name, location, …, annotation, codeICAOCountry, fix
    `designator`/`name` bilinçli olarak boş — tanımlayıcı bilgi annotation'da.
    """
    member = etree.Element(M + "hasMember", nsmap=NSMAP)
    feature = etree.SubElement(member, A + "DesignatedPoint")
    feature.set(G + "id", gml_id)

    ident = etree.SubElement(feature, G + "identifier")
    ident.set("codeSpace", "urn:uuid:")
    ident.text = point_uuid

    wrapper = etree.SubElement(feature, A + "timeSlice")
    ts = etree.SubElement(wrapper, A + "DesignatedPointTimeSlice")
    ts.set(G + "id", gml_id + "_TS")

    # Yürürlük bilgisi bölünen segmentten devralınır (uydurulmaz). Kopyalanan
    # alt elemanların gml:id'leri kaynağınkini taşır; bu feature'a ait olacak
    # şekilde yeniden adlandırılır.
    valid_time = copy.deepcopy(valid_time_source)
    for el in valid_time.iter():
        if el.get(G + "id"):
            el.set(G + "id", gml_id + "_TP")
    ts.append(valid_time)
    etree.SubElement(ts, A + "interpretation").text = "BASELINE"
    etree.SubElement(ts, A + "sequenceNumber").text = "1"
    etree.SubElement(ts, A + "correctionNumber").text = "0"

    etree.SubElement(ts, A + "type").text = "OTHER"

    location = etree.SubElement(ts, A + "location")
    point = etree.SubElement(location, A + "Point")
    point.set(G + "id", gml_id + "_P")
    point.set("srsName", SRS_NAME)
    etree.SubElement(point, G + "pos").text = f"{lat} {lon}"

    _add_note(ts, gml_id, POINT_NOTE, "NOTE")
    return member


def split_member(member, info):
    """Antimeridyeni aşan bir RouteSegment'i böler.

    → `[hasMember, …]` (ara nokta + iki segment) veya bölme yapılamıyorsa `None`
    (çağıran orijinali olduğu gibi yazar ve durumu loglar).
    """
    positions = info.get("positions")
    if not crosses_antimeridian(positions):
        return None

    (lat1, lon1), (lat2, lon2) = positions[0], positions[-1]
    lat_cross = crossing_latitude(lat1, lon1, lat2, lon2)
    if lat_cross is None:
        return None

    feature = member[0]
    ts = time_slice(feature)
    if ts is None:
        return None
    valid_time = ts.find(G + "validTime")
    if valid_time is None:
        return None

    base_id = info["gml_id"]
    base_uuid = info["uuid"] or base_id

    # A segmenti başlangıç ucunun işaretiyle biter, B karşı işaretle başlar.
    lon_a = 180.0 if lon1 > 0 else -180.0
    lon_b = -lon_a

    point_id = f"{base_id}_AM_PT"
    point_uuid = _derived_uuid("AntimeridianPoint", base_uuid)
    # Paylaşılan ara nokta tek konumda tutulur: +180 (aynı meridyen).
    point_member = _build_crossing_point(
        point_id, point_uuid, lat_cross, 180.0, valid_time)

    halves = []
    for suffix, side_to_replace, coords in (
        ("A", "end", [(lat1, lon1), (lat_cross, lon_a)]),
        ("B", "start", [(lat_cross, lon_b), (lat2, lon2)]),
    ):
        clone = copy.deepcopy(member)
        clone_feature = clone[0]
        new_id = f"{base_id}_AM_{suffix}"
        _set_gml_ids(clone_feature, base_id, new_id)

        ident = clone_feature.find(G + "identifier")
        if ident is not None:
            ident.text = _derived_uuid(f"AntimeridianSegment{suffix}", base_uuid)

        clone_ts = time_slice(clone_feature)
        if not _replace_endpoint(clone_ts, side_to_replace, point_uuid):
            return None
        _set_curve(clone_ts, coords)
        _add_note(clone_ts, new_id, SEGMENT_NOTE, "AMNOTE")
        halves.append(clone)

    return [point_member] + halves
