r"""Jeppesen (Navigraph) NDB verisini AIXM 5.2 XML'ine dönüştürür.

Girdi : ..\..\..\..\Jeppesen Data\jeppesen.sqlite  (yalnızca `ndb` tablosu)
        ..\..\..\..\Jeppesen Data\data.json               (provenance)
Çıktı : ../jeppesen-ndb-aixm.xml        — AIXM 5.2
        ../jeppesen-ndb-index.json      — EAD-SDO üreticisinin referans
                                          çözümlemesi için (ident+region → uuid)
        ../data.json                    — kaynağın yanındaki data.json'ın
                                          birebir kopyası (elle düzenlenmez)
Log   : errored-features.log            — her çalıştırmada sıfırlanır

Neden ayrı bir kaynak: EAD-SDO SDO raporlarında NDB raporu bulunmuyor, ancak
EAD rota kayıtları 3.040 kez NDB'ye referans veriyor. Bu NDB'ler Jeppesen'den
üretilip ayrı bir AIXM dosyasında tutulur; EAD-SDO üreticisi kendi dosyasına
NDB YAZMAZ, yalnızca buradaki NDB'lere xlink ile referans verir.

Her NDB için iki AIXM feature'ı üretilir (gerçek AIXM yapısı):
  Navaid (type=NDB)  --navaidEquipment--> NavaidComponent --theNavaidEquipment-->
  NDB (AbstractNavaidEquipment somut alt-türü, kendi konumu/frekansı ile)

Tüm alan eşlemeleri ve gerekçeleri Jeppesen_to_AIXM_Mapping.md'de.
"""

import json
import sqlite3
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(BASE_DIR))

from aixm_writer import (  # noqa: E402
    IdRegistry, MessageBuilder, NS_GML, aixm, elevated_point, feature_uuid,
    note, opt, q, sub, xlink_ref,
)

JEPPESEN_DIR = BASE_DIR.parent
SOURCE_DIR = Path(
    r"D:\ibosoft\aeronautical-charting\aeronautical-data\Jeppesen Data"
)
SQLITE_PATH = SOURCE_DIR / "jeppesen.sqlite"
# Provenance bilgisi kaynağın yanındaki data.json'dan okunur ve buraya
# aynen yazılır — bu dosya bir ÇIKTIDIR, elle düzenlenmez.
SOURCE_DATA_JSON = SOURCE_DIR / "data.json"
OUTPUT_XML = JEPPESEN_DIR / "jeppesen-ndb-aixm.xml"
OUTPUT_INDEX = JEPPESEN_DIR / "jeppesen-ndb-index.json"
OUTPUT_DATA_JSON = JEPPESEN_DIR / "data.json"
LOG_PATH = BASE_DIR / "errored-features.log"

HEADER_COMMENT = "Generated by Ibosoft AIS - ais.ibosoft.net.tr"

# AIXM CodeNDBUsageType (XSD'den birebir)
CODE_NDB_USAGE = {"ENR", "L", "MAR"}

# Jeppesen ndb.type → AIXM NDB.class eşlemesi.
# Kullanıcı kararı: yalnızca CP (Compass Locator) eşlenir — AIXM `L` (Locator)
# ile birebir aynı kavramdır. `H`/`MH` ARINC GÜÇ sınıflarıdır, AIXM'in
# KULLANIM sınıfı (ENR/L/MAR) ile aynı kavram değildir; uydurma eşleme
# yapılmaz, ham değer annotation'da saklanır.
NDB_TYPE_TO_CLASS = {"CP": "L"}


class ErrorLog:
    """Satır formatı: SEVERITY | FEATURE | ID | FIELD | VALUE | VIOLATION"""

    def __init__(self, path: Path):
        self.counts: dict[str, int] = {}
        self._fh = open(path, "w", encoding="utf-8")
        self._fh.write("SEVERITY | FEATURE | ID | FIELD | VALUE | VIOLATION\n")

    def log(self, severity, feature, ident, field, value, violation):
        self.counts[violation] = self.counts.get(violation, 0) + 1
        parts = [severity, feature, str(ident), str(field), str(value), violation]
        self._fh.write(" | ".join(p.replace("|", "/") for p in parts) + "\n")

    def error(self, *args):
        self.log("ERROR", *args)

    def warning(self, *args):
        self.log("WARNING", *args)

    def summary(self):
        return dict(sorted(self.counts.items()))

    def close(self):
        self._fh.close()


def load_source_meta(log) -> dict:
    """Kaynağın yanındaki data.json'ı okur ve bu kaynak dizinine aynen yazar.

    `data-sources/Jeppesen/data.json` elle tutulan bir dosya DEĞİLDİR; her
    çalıştırmada `Jeppesen Data/data.json`'dan birebir kopyalanır ki provenance
    bilgisi tek bir yerde (verinin kendi yanında) yönetilsin.
    """
    try:
        meta = json.loads(SOURCE_DATA_JSON.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        log.error("Message", "-", "data.json", str(SOURCE_DATA_JSON),
                  "kaynak_data_json_okunamadi")
        print(f"  UYARI: {SOURCE_DATA_JSON} okunamadi ({exc})")
        return {}
    OUTPUT_DATA_JSON.write_text(
        json.dumps(meta, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return meta


def load_effectivity(meta, log) -> str:
    """data.json'daki geçerlilik metninden AIXM beginPosition üretir.

    "06 AUG 2026 (AIRAC 2608)" gibi tam tarih varsa **doğrudan onu** kullanır.
    Yalnızca döngü numarası yazılıysa ("AIRAC 2608") tarih 28 günlük ICAO AIRAC
    takviminden hesaplanır.

    Çapa tarihi projedeki mevcut veriden doğrulandı: `Designated Points\\EAD-SDO`
    ve `LT` data.json'ları AIRAC 2607'yi 09 JUL 2026, 2608'i 06 AUG 2026 olarak
    veriyor (tam 28 gün fark). Buradan geriye: AIRAC 2601 = 22 JAN 2026.
    """
    import re
    from datetime import date, timedelta

    months = {"JAN": 1, "FEB": 2, "MAR": 3, "APR": 4, "MAY": 5, "JUN": 6,
              "JUL": 7, "AUG": 8, "SEP": 9, "OCT": 10, "NOV": 11, "DEC": 12}
    raw = (meta or {}).get("data_effectivity", "") or ""

    m = re.match(r"\s*(\d{1,2})\s+([A-Z]{3})\s+(\d{4})", raw.upper())
    if m:
        return f"{int(m.group(3)):04d}-{months[m.group(2)]:02d}-{int(m.group(1)):02d}T00:00:00Z"

    m = re.search(r"(\d{2})(\d{2})", raw)
    if m:
        year, cycle = 2000 + int(m.group(1)), int(m.group(2))
        anchor = {2026: date(2026, 1, 22)}.get(year)   # AIRAC 2601 = 22 JAN 2026
        if anchor:
            return (anchor + timedelta(days=28 * (cycle - 1))).strftime("%Y-%m-%dT00:00:00Z")

    log.error("Message", "-", "data_effectivity", raw, "yururluk_tarihi_cozulemedi")
    return date.today().strftime("%Y-%m-%dT00:00:00Z")


def load_ndb_rows() -> list[dict]:
    con = sqlite3.connect(SQLITE_PATH)
    con.row_factory = sqlite3.Row
    cur = con.cursor()
    cur.execute(
        "SELECT ndb_id, ident, name, region, type, frequency, range, mag_var, "
        "       altitude, lonx, laty "
        "FROM ndb ORDER BY ident, region, ndb_id"
    )
    rows = [dict(r) for r in cur.fetchall()]
    con.close()
    return rows


def khz(raw_frequency) -> str | None:
    """Jeppesen frekansı 100 Hz biriminde saklar: 32000 → 320 kHz.

    Doğrulandı: değer aralığı 19800-173000 → 198-1730 kHz, ICAO NDB bandıyla
    (190-1750 kHz) birebir örtüşüyor.
    """
    if raw_frequency is None:
        return None
    value = raw_frequency / 100.0
    return str(int(value)) if value == int(value) else str(value)


def num(value) -> str | None:
    if value is None:
        return None
    return str(int(value)) if float(value) == int(value) else f"{float(value):.6f}"


def write_ndb_equipment(builder, ids, log, row, gml_id, uuid_value):
    """AbstractNavaidEquipment somut alt-türü: <aixm:NDB>.

    XSD sırası: NavaidEquipmentPropertyGroup (designator, name, emissionClass,
    mobile, magneticVariation, dateMagneticVariation, flightChecked, location,
    authority, monitoring, availability, annotation) → frequency, class,
    emissionBand
    """
    ts = builder.add_feature("NDB", gml_id, uuid_value)

    opt(ts, aixm("designator"), row["ident"])
    opt(ts, aixm("name"), row["name"])
    # mag_var işaret konvansiyonu doğrulandı: pozitif = DOĞU (Ottawa -12.5 =
    # 12.5°W, Moskova +11.5 = 11.5°E, Alaska +15 = 15°E gerçek değerlerle
    # örtüşüyor) — AIXM ValMagneticVariationType ile birebir aynı, dönüşüm yok.
    opt(ts, aixm("magneticVariation"), num(row["mag_var"]))
    elevated_point(ts, gml_id + "_EP", row["laty"], row["lonx"])

    # `type` eşlenemiyorsa ham değeri kaybetmemek için not düşülür.
    raw_type = (row["type"] or "").strip().upper()
    if raw_type and raw_type not in NDB_TYPE_TO_CLASS:
        note(ts, gml_id + "_NOTE",
             f"Jeppesen NDB type: {raw_type} (ARINC guc sinifi; AIXM "
             f"CodeNDBUsageType kullanim sinifi ile ayni kavram degildir)")

    opt(ts, aixm("frequency"), khz(row["frequency"]), uom="KHZ")

    ndb_class = NDB_TYPE_TO_CLASS.get(raw_type)
    if ndb_class:
        if ndb_class not in CODE_NDB_USAGE:
            log.error("NDB", gml_id, "class", ndb_class, "enum_disi_deger")
        sub(ts, aixm("class"), ndb_class)


def write_navaid(builder, ids, log, row, gml_id, uuid_value, equipment_uuid):
    """Rota uç noktalarının referans verdiği <aixm:Navaid> (type=NDB).

    XSD sırası: type, designator, name, flightChecked, purpose,
    signalPerformance, courseQuality, integrityLevel, touchDownLiftOff,
    navaidEquipment, location, runwayDirection, servedAirport, availability,
    annotation, codeICAOCountry
    """
    ts = builder.add_feature("Navaid", gml_id, uuid_value)

    sub(ts, aixm("type"), "NDB")
    opt(ts, aixm("designator"), row["ident"])
    opt(ts, aixm("name"), row["name"])

    # navaidEquipment, location'dan ÖNCE gelir (XSD sırası).
    eq = ET.SubElement(ts, aixm("navaidEquipment"))
    comp = ET.SubElement(eq, aixm("NavaidComponent"))
    comp.set(q(NS_GML, "id"), gml_id + "_NC")
    # Navaid'in navigasyona esas konumunu bu bileşen belirler.
    sub(comp, aixm("providesNavigableLocation"), "YES")
    xlink_ref(comp, aixm("theNavaidEquipment"), equipment_uuid)

    elevated_point(ts, gml_id + "_EP", row["laty"], row["lonx"])


def main():
    if not SQLITE_PATH.exists():
        print(f"HATA: {SQLITE_PATH} bulunamadi.")
        return 1

    log = ErrorLog(LOG_PATH)
    ids = IdRegistry("JEPP")
    meta = load_source_meta(log)
    builder = MessageBuilder("JEPP_MSG_NDB", load_effectivity(meta, log))

    rows = load_ndb_rows()
    index: list[dict] = []
    skipped = 0

    for row in rows:
        ident = (row["ident"] or "").strip().upper()
        region = (row["region"] or "").strip().upper()
        if not ident or row["laty"] is None or row["lonx"] is None:
            skipped += 1
            log.error("NDB", row["ndb_id"], "ident/laty/lonx", ident,
                      "zorunlu_alan_eksik")
            continue

        key = f"{ident}:{region}:{row['ndb_id']}"
        eq_gml = ids.make("NDBEQ", f"{ident}_{region}")
        nav_gml = ids.make("NAV_NDB", f"{ident}_{region}")
        eq_uuid = feature_uuid("JeppesenNdbEquipment", key)
        nav_uuid = feature_uuid("JeppesenNdbNavaid", key)

        write_ndb_equipment(builder, ids, log, row, eq_gml, eq_uuid)
        write_navaid(builder, ids, log, row, nav_gml, nav_uuid, eq_uuid)

        index.append({
            "designator": ident,
            "region": region,
            "navaid_uuid": nav_uuid,
            "equipment_uuid": eq_uuid,
            "lat": row["laty"],
            "lon": row["lonx"],
        })

    builder.write(OUTPUT_XML, HEADER_COMMENT)
    OUTPUT_INDEX.write_text(
        json.dumps(index, ensure_ascii=False, indent=1), encoding="utf-8")

    print("=" * 60)
    print(f"Cikti : {OUTPUT_XML}")
    print(f"Index : {OUTPUT_INDEX}")
    print(f"  ndb tablosu okunan : {len(rows)}")
    print(f"  atlanan (eksik alan): {skipped}")
    print(f"  Navaid (type=NDB)  : {len(index)}")
    print(f"  NDB (equipment)    : {len(index)}")
    print(f"  TOPLAM feature     : {2 * len(index)}")
    summary = log.summary()
    print(f"\nerrored-features.log: {sum(summary.values())} kayit")
    for k, v in summary.items():
        print(f"  {k:34} {v}")
    log.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
