r"""EAD-SDO ham raporlarını AIXM 5.2 XML'ine dönüştürür.

Girdi : ../raw-data/  (dp-*.xml, vor/dme/tacan/ils-loc/ils-gp.xml, routes-*.xml)
        ../../Jeppesen/jeppesen-ndb-index.json  (NDB uç noktası referansları)
Çıktı : ../ead-sdo-aixm.xml            — AIXM 5.2
        ../ead-sdo-originators.json    — gml:id → originator (AIXM'de originator
                                         alanı yoktur; EAD'de her kaydın kendi
                                         OrgCre/txtName'i farklıdır)
Log   : errored-features.log           — her çalıştırmada sıfırlanır

Navaid eşleştirme mantığı `Navaids\EAD-SDO\build_navaids_gpkg.py` dosyasından
birebir port edilmiştir (bkz. matching.py). Tüm alan/enum eşlemeleri
mapping.py'de, gerekçeleri EAD-SDO_Field_Mapping.md'de.

NDB: EAD-SDO'da NDB raporu yoktur. NDB'ler ayrı bir kaynaktan (Jeppesen)
üretilir; bu script kendi dosyasına NDB YAZMAZ, yalnızca Jeppesen dosyasındaki
NDB'lere xlink ile referans verir.
"""

import json
import math
import sys
from collections import defaultdict
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(BASE_DIR))

import features                                              # noqa: E402
import mapping                                               # noqa: E402
import matching                                              # noqa: E402
from aixm_writer import IdRegistry, MessageBuilder, feature_uuid   # noqa: E402

EAD_DIR = BASE_DIR.parent
RAW_DIR = EAD_DIR / "raw-data"
OUTPUT_XML = EAD_DIR / "ead-sdo-aixm.xml"
OUTPUT_ORIGINATORS = EAD_DIR / "ead-sdo-originators.json"
JEPPESEN_INDEX = EAD_DIR.parent / "Jeppesen" / "jeppesen-ndb-index.json"
FREQUENCY_PAIRING = BASE_DIR / "frequency-pairing.csv"
LOG_PATH = BASE_DIR / "errored-features.log"

HEADER_COMMENT = "Generated by Ibosoft AIS - ais.ibosoft.net.tr"

DP_FILES = [RAW_DIR / f"dp-{r}.xml" for r in ("ne", "nw", "se")]
ROUTE_FILES = (
    [(RAW_DIR / f"routes-upper-{r}.xml", "UPPER") for r in ("ne", "nw", "se", "sw")]
    + [(RAW_DIR / f"routes-non-upper-{r}.xml", "LOWER") for r in ("ne", "nw", "se", "sw")]
)


class ErrorLog:
    """Satır formatı: SEVERITY | FEATURE | ID | FIELD | VALUE | VIOLATION"""

    def __init__(self, path: Path):
        self.counts: dict[str, int] = {}
        self._fh = open(path, "w", encoding="utf-8")
        self._fh.write("SEVERITY | FEATURE | ID | FIELD | VALUE | VIOLATION\n")

    def log(self, severity, feature, ident, field, value, violation):
        self.counts[violation] = self.counts.get(violation, 0) + 1
        parts = [severity, feature, str(ident), str(field), str(value), violation]
        self._fh.write(" | ".join(p.replace("|", "/") for p in parts) + "\n")

    def error(self, *a):
        self.log("ERROR", *a)

    def warning(self, *a):
        self.log("WARNING", *a)

    def summary(self):
        return dict(sorted(self.counts.items()))

    def close(self):
        self._fh.close()


# ── Uç nokta çözümleyici ────────────────────────────────────────────────────

class EndpointResolver:
    """Rota uç noktalarını çözer — segmentin İKİ UCU BİRLİKTE.

    Kullanıcı onaylı strateji (v2 — coğrafi yakınlık):
      1. Her uç için ident (+tip) ile aday listesi çıkarılır; seçim yapılmaz.
      2. İki ucun da adayı varsa, aday çiftleri arasından **segment uzunluğunu
         en küçük yapan** çift seçilir.
      3. Eşitlik durumunda rotanın originator'ı ikincil ölçüt olarak kullanılır.
      4. Bir ucun hiç adayı yoksa (dayanak nokta yok), diğer uç yalnızca
         originator ile ayıklanır; ayıklanamazsa çözülmez ve loglanır.

    **Neden originator ayıklaması tek başına yetmiyor:** rota kaydının
    `OrgCre/txtName`'i ROTAYI yayımlayan kurumdur, noktayı yayımlayan değil
    (rotalar sınır aşar). Aynı designator dünyanın iki ayrı yerinde varsa,
    originator ayıklaması coğrafi olarak YANLIŞ olanı seçebiliyordu — ölçüldü:
    233 segment 2000 NM'den uzun çıkmıştı (en uzunu 10.287 NM), örn. `UL210`
    rotasında Bahamalar'daki `UMIMI`den Tayvan'daki `BORDO`ya. Rota segmentleri
    kısa olduğu için (%98,1'i < 300 NM) yakınlık çok daha güçlü bir sinyaldir.
    """

    # Seçilen en iyi çift bu eşiği aşıyorsa eşleşme KABUL EDİLMEZ (kullanıcı
    # kararı, eşik 1000 NM). Böyle durumlarda doğru nokta kaynakta hiç
    # bulunmuyor demektir — algoritma "en az kötü" adayı seçmiş oluyor ki bu
    # kesinlikle yanlış bir referanstır. Kullanıcının baştan beri geçerli olan
    # ilkesi: yanlış eşleşme üretmektense çözümsüz bırak ve logla.
    MAX_SEGMENT_NM = 1000

    def __init__(self, log):
        self.log = log
        self.dp_by_designator = defaultdict(list)       # designator → [entry]
        self.navaid_by_designator = defaultdict(list)   # designator → [entry]
        self.ndb_by_designator = defaultdict(list)      # designator → [entry]
        self.stats = defaultdict(int)

    # -- indeks kurulumu --
    def add_dp(self, designator, dp_type, originator, uuid_value, lat, lon):
        self.dp_by_designator[designator].append(
            {"type": dp_type, "originator": originator, "uuid": uuid_value,
             "lat": lat, "lon": lon})

    def add_navaid(self, designator, aixm_type, originator, uuid_value, lat, lon):
        self.navaid_by_designator[designator].append(
            {"type": aixm_type, "originator": originator, "uuid": uuid_value,
             "lat": lat, "lon": lon})

    def load_jeppesen_ndb(self, path: Path):
        if not path.exists():
            self.log.error("RouteSegment", "-", "jeppesen-ndb-index.json",
                           str(path), "ndb_kaynagi_bulunamadi")
            return 0
        for row in json.loads(path.read_text(encoding="utf-8")):
            self.ndb_by_designator[row["designator"]].append(
                {"region": row.get("region"), "uuid": row["navaid_uuid"],
                 "lat": row["lat"], "lon": row["lon"]})
        return sum(len(v) for v in self.ndb_by_designator.values())

    # -- aday listeleri (seçim yapılmaz) --

    def candidates(self, code_id, code_type, loc_designator):
        """→ (kind, [aday…], etiket). Aday seçimi yapmaz.

        `etiket` log/istatistik için uç nokta tipini taşır ("WPT", "NDB",
        "VOR/DME" …).
        """
        if not code_id:
            return None, [], "bos"

        ctype = mapping.ENDPOINT_TYPE_ALIAS.get(code_type, code_type)

        if ctype == "WPT":
            cands = self.dp_by_designator.get(code_id, [])
            # Rota uç noktaları kural olarak ICAO tiplidir; yoksa diğerleri.
            icao = [c for c in cands if c["type"] == "ICAO"]
            return "DP", (icao or list(cands)), "WPT"

        if ctype == "NDB":
            cands = list(self.ndb_by_designator.get(code_id, []))
            if len(cands) > 1:
                # Bölge kodu ayıklaması yakınlıktan ÖNCE uygulanır: Jeppesen
                # NDB ident'leri sık tekrar ettiği için aday sayısını
                # anlamlı biçimde düşürür.
                regions = mapping.regions_of(loc_designator)
                hit = [c for c in cands if c.get("region") in regions]
                if hit:
                    cands = hit
            return "NAVAID", cands, "NDB"

        # İşlevsel eşdeğerlik: aynı tesis AIP'de ve EAD'de farklı tiplerle
        # modellenebiliyor (bkz. mapping.ENDPOINT_TO_NAVAID_TYPES). Katı
        # eşitlik doğru adayı eliyor, geriye coğrafi olarak yanlış tek aday
        # kalıyor ve aşağıdaki yakınlık ayıklaması devreye giremiyordu.
        wanted = mapping.ENDPOINT_TO_NAVAID_TYPES.get(ctype)
        if wanted is None:
            return None, [], ctype
        return "NAVAID", [c for c in self.navaid_by_designator.get(code_id, [])
                          if c["type"] in wanted], ctype

    # -- çözümleme --

    @staticmethod
    def _nm(a, b):
        """İki aday arasındaki büyük daire mesafesi (NM).

        Aday seçmek için yeterli hassasiyette; haversine antimeridyende de
        doğru çalışır (boylam farkının sinüs/kosinüsü kullanılır).
        """
        r = 3440.065
        p1, p2 = math.radians(a["lat"]), math.radians(b["lat"])
        dp = math.radians(b["lat"] - a["lat"])
        dl = math.radians(b["lon"] - a["lon"])
        h = (math.sin(dp / 2) ** 2
             + math.cos(p1) * math.cos(p2) * math.sin(dl / 2) ** 2)
        return 2 * r * math.asin(min(1.0, math.sqrt(h)))

    def _alone(self, cands, originator, gml_id, code_id, label):
        """Dayanak nokta yokken tek adaya indirger (eski davranış)."""
        if len(cands) > 1:
            hit = [c for c in cands if c.get("originator") == originator]
            if len(hit) == 1:
                return hit[0]
            self.stats[f"{label}_belirsiz"] += 1
            self.log.warning("RouteSegment", gml_id, label, code_id,
                             "birden_fazla_aday_ayiklanamadi")
            return None
        return cands[0] if cands else None

    def resolve_segment(self, rec, gml_id):
        """Segmentin iki ucunu birlikte çözer.

        → {"start": (uuid, kind, (lat, lon)) | (None, None, None), "end": …}
        """
        picked = {}
        info = {}
        for side in ("start", "end"):
            kind, cands, label = self.candidates(
                rec[f"{side}_code_id"], rec[f"{side}_code_type"],
                rec["loc_designator"])
            info[side] = (kind, cands, label)
            if not rec[f"{side}_code_id"]:
                self.stats["bos_code_id"] += 1
            elif not cands:
                self.stats[f"{label}_bulunamadi"] += 1
                self.log.warning("RouteSegment", gml_id, label,
                                 rec[f"{side}_code_id"], "uc_nokta_cozulemedi")

        (s_kind, s_cands, s_label) = info["start"]
        (e_kind, e_cands, e_label) = info["end"]
        originator = rec["created_by"]

        if s_cands and e_cands:
            # Coğrafi yakınlık birincil ölçüt; originator yalnızca eşitlik
            # bozucu (rotanın originator'ı noktanınkiyle aynı olmak zorunda
            # değil, bu yüzden tek başına güvenilir değil).
            best = min(
                ((self._nm(a, b), a, b) for a in s_cands for b in e_cands),
                key=lambda t: (round(t[0], 6),
                               0 if t[1].get("originator") == originator else 1,
                               0 if t[2].get("originator") == originator else 1))
            distance, a, b = best
            if distance > self.MAX_SEGMENT_NM:
                # En iyi çift bile eşiği aşıyor → doğru nokta kaynakta yok.
                # Yanlış referans yazmaktansa iki ucu da çözümsüz bırak.
                self.stats["esik_asildi_cozulmedi"] += 1
                self.log.warning("RouteSegment", gml_id, "segment",
                                 f"{rec['start_code_id']}->{rec['end_code_id']}"
                                 f" ({distance:.0f} NM)",
                                 "en_iyi_cift_esigi_asti_cozulmedi")
            else:
                picked["start"], picked["end"] = a, b
                if len(s_cands) > 1 or len(e_cands) > 1:
                    self.stats["yakinlikla_ayiklandi"] += 1
        else:
            # Bir uç çözülemiyor → dayanak yok, diğer uç yalnız ayıklanır.
            if s_cands:
                picked["start"] = self._alone(s_cands, originator, gml_id,
                                              rec["start_code_id"], s_label)
            if e_cands:
                picked["end"] = self._alone(e_cands, originator, gml_id,
                                            rec["end_code_id"], e_label)

        out = {}
        for side, kind, label in (("start", s_kind, s_label),
                                  ("end", e_kind, e_label)):
            c = picked.get(side)
            if c is None:
                out[side] = (None, None, None)
                continue
            counter = ("dp_cozuldu" if kind == "DP"
                       else "ndb_cozuldu" if label == "NDB"
                       else "navaid_cozuldu")
            self.stats[counter] += 1
            out[side] = (c["uuid"], kind, (c["lat"], c["lon"]))
        return out


# ── Ana akış ───────────────────────────────────────────────────────────────

def main():
    log = ErrorLog(LOG_PATH)
    ids = IdRegistry("EAD")
    builder = MessageBuilder(OUTPUT_XML, "EAD_MSG_SDO", HEADER_COMMENT)
    resolver = EndpointResolver(log)
    originators: dict[str, str] = {}
    counts: dict[str, int] = {}

    def remember(gml_id, originator):
        """AIXM'de originator alanı yok — gml:id bazlı yan dosyada tutulur."""
        if originator:
            originators[gml_id] = originator

    print("=" * 60)
    print("EAD-SDO -> AIXM 5.2")
    print("=" * 60)

    # ── 1. DesignatedPoint ──────────────────────────────────────────────────
    print("\n[1] DesignatedPoint okunuyor...")
    dp_records = matching.load_designated_points(DP_FILES)
    for rec in dp_records:
        gml_id = ids.make("DP", f"{rec['code_id']}_{rec['mid']}")
        uid = feature_uuid("EadDesignatedPoint", rec["mid"] or gml_id)
        features.write_designated_point(
            builder, log, gml_id, uid, rec, mapping.parse_dt_wef(rec["dt_wef"]))
        remember(gml_id, rec["created_by"])
        resolver.add_dp(rec["code_id"], rec["code_type"], rec["created_by"],
                        uid, rec["lat_dd"], rec["lon_dd"])
    counts["DesignatedPoint"] = len(dp_records)

    # ── 2. Navaid + NavaidEquipment ─────────────────────────────────────────
    print("\n[2] Navaid kaynakları okunuyor ve eşleştiriliyor...")
    dme_records = matching.load_dme_records(RAW_DIR / "dme.xml")
    tacan_records = matching.load_tacan_records(RAW_DIR / "tacan.xml")
    gp_index = matching.load_gp_records(RAW_DIR / "ils-gp.xml")
    loc_groups, dme_by_ils = matching.load_loc_groups(
        RAW_DIR / "ils-loc.xml", gp_index, dme_records)
    vor_groups, dme_by_vor, tacan_by_vor = matching.load_vor_groups(
        RAW_DIR / "vor.xml", dme_records, tacan_records)
    dme_groups, tacan_groups = matching.collect_standalone(
        dme_records, tacan_records, dme_by_ils | dme_by_vor, tacan_by_vor)

    channel_to_vhf, vhf_to_channel, _, _ = mapping.load_frequency_pairing(
        FREQUENCY_PAIRING)

    def tuning_vhf(rec):
        """DME/TACAN için eşleştirilmiş VHF frekansı.

        Ham `valGhostFreq` varsa o kullanılır; yoksa legacy'deki
        frequency-pairing tablosundan kanal numarasına göre bulunur
        (legacy `enrich_frequency_fields` ile aynı yön).
        """
        if rec.get("ghost_freq"):
            return mapping.number(rec["ghost_freq"])
        channel = (rec.get("channel") or "").strip().upper()
        return channel_to_vhf.get(channel)

    equipment_written: dict[tuple[str, str], str] = {}

    def write_equipment(kind, rec, key_prefix):
        """Bir ham kaydı uygun AIXM ekipman feature'ı olarak yazar → uuid.

        Aynı ekipman birden fazla Navaid tarafından eşleştirilebilir: eşleştirme
        motoru (legacy'den birebir port) `dme_records` üzerinde dolaşıp ilk
        uyanı alır ve bir VOR'un eşleşmesi başka bir VOR'un aynı DME'yi
        eşleştirmesini engellemez — kaynakta aynı `codeId` + `OrgCre/txtName`
        ikilisini taşıyan birden fazla VOR/TACAN kaydı bulunuyor.

        Legacy'de bu, düz satırlarda verinin tekrar yazılması demekti (zararsız).
        AIXM'de her feature'ın tekil `gml:identifier`'ı olduğu için ekipman
        **bir kez** yazılır ve onu eşleştiren tüm Navaid'ler aynı UUID'ye
        referans verir. Eşleştirme KARARLARI değişmez — yalnızca yazım tekilleşir.
        """
        cache_key = (kind, rec.get("mid") or "")
        if cache_key in equipment_written:
            return equipment_written[cache_key]

        gml_id = ids.make(key_prefix, f"{rec.get('code_id')}_{rec.get('mid')}")
        uid = feature_uuid(f"Ead{kind}", rec.get("mid") or gml_id)
        valid = mapping.parse_dt_wef(rec.get("dt_wef"))
        if kind == "VOR":
            features.write_vor_equipment(builder, log, gml_id, uid, rec, valid)
        elif kind == "DME":
            features.write_dme_equipment(builder, log, gml_id, uid, rec, valid,
                                         tuning_vhf(rec))
        elif kind == "TACAN":
            features.write_tacan_equipment(builder, log, gml_id, uid, rec, valid,
                                           tuning_vhf(rec))
        elif kind == "Localizer":
            features.write_localizer_equipment(builder, log, gml_id, uid, rec, valid)
        elif kind == "Glidepath":
            features.write_glidepath_equipment(builder, log, gml_id, uid, rec, valid)
        remember(gml_id, rec.get("created_by"))
        counts[f"NavaidEquipment/{kind}"] = counts.get(f"NavaidEquipment/{kind}", 0) + 1
        equipment_written[cache_key] = uid
        return uid

    def write_group(group):
        primary = group["primary"]
        components = []
        if group["kind"] == "LOC":
            components.append((write_equipment("Localizer", primary, "LOC"), True))
            if group.get("gp"):
                components.append((write_equipment("Glidepath", group["gp"], "GP"), False))
            if group.get("dme"):
                components.append((write_equipment("DME", group["dme"], "DME"), False))
        elif group["kind"] == "VOR":
            components.append((write_equipment("VOR", primary, "VOR"), True))
            if group.get("tacan"):
                components.append((write_equipment("TACAN", group["tacan"], "TAC"), False))
            if group.get("dme"):
                components.append((write_equipment("DME", group["dme"], "DME"), False))
        elif group["kind"] == "DME":
            components.append((write_equipment("DME", primary, "DME"), True))
        elif group["kind"] == "TACAN":
            components.append((write_equipment("TACAN", primary, "TAC"), True))

        gml_id = ids.make("NAV", f"{primary.get('code_id')}_{primary.get('mid')}")
        uid = feature_uuid("EadNavaid", f"{group['aixm_type']}:{primary.get('mid')}")
        features.write_navaid(builder, log, gml_id, uid, primary,
                              group["aixm_type"], components,
                              mapping.parse_dt_wef(primary.get("dt_wef")))
        remember(gml_id, primary.get("created_by"))
        resolver.add_navaid(primary["code_id"], group["aixm_type"],
                            primary.get("created_by"), uid,
                            primary["lat_dd"], primary["lon_dd"])
        counts["Navaid"] = counts.get("Navaid", 0) + 1

    for group in loc_groups + vor_groups + dme_groups + tacan_groups:
        write_group(group)

    # Hiçbir LOC ile eşleşmeyen GP'ler: kendi ekipman feature'ları yazılır
    # (haritalama değeri kaybolmasın diye) ama bir Navaid'e bağlanmazlar —
    # GP tek başına geçerli bir CodeNavaidServiceType değildir.
    matched_gp_keys = {
        (g["gp"]["mid"]) for g in loc_groups if g.get("gp") and g["gp"].get("mid")
    }
    orphan_gp = 0
    for gp in gp_index.values():
        if gp.get("mid") in matched_gp_keys:
            continue
        write_equipment("Glidepath", gp, "GP")
        log.warning("Glidepath", gp.get("mid"), "Ilz/codeId", gp.get("code_id"),
                    "eslesmeyen_gp_navaid_e_baglanmadi")
        orphan_gp += 1
    counts["Glidepath (eslesmeyen)"] = orphan_gp

    # ── 3. NDB kaynağı (Jeppesen) ───────────────────────────────────────────
    print("\n[3] Jeppesen NDB indeksi yükleniyor...")
    n_ndb = resolver.load_jeppesen_ndb(JEPPESEN_INDEX)
    print(f"  NDB kaydi (referans icin): {n_ndb}")

    # ── 4. Route ────────────────────────────────────────────────────────────
    print("\n[4] Rotalar okunuyor...")
    route_records = matching.load_route_records(ROUTE_FILES)

    # Bölge sınırını kesen bir segment birden fazla yarımküre raporunda
    # görünüyor: 619 `mid` iki dosyada birden geçiyor. Doğrulandı — bu
    # kopyalar `level` dahil TÜM alanlarda birebir aynı, yalnızca geldikleri
    # dosya farklı. AIXM'de her feature tekil `gml:identifier` taşımak zorunda
    # olduğu için `mid` bazında tekilleştirilir (veri kaybı yok).
    seen_mids: set[str] = set()
    deduped: list[dict] = []
    for rec in route_records:
        mid = rec.get("mid")
        if mid and mid in seen_mids:
            continue
        if mid:
            seen_mids.add(mid)
        deduped.append(rec)
    duplicate_segments = len(route_records) - len(deduped)
    if duplicate_segments:
        print(f"  Birden fazla raporda gecen segment (tekillestirildi): "
              f"{duplicate_segments}")
    route_records = deduped

    route_uuids: dict[tuple[str, str], str] = {}
    for rec in route_records:
        key = (rec["designator"] or "", rec["loc_designator"] or "")
        if not rec["designator"] or key in route_uuids:
            continue
        gml_id = ids.make("RTE", f"{rec['designator']}_{rec['loc_designator'] or 'X'}")
        uid = feature_uuid("EadRoute", f"{key[0]}|{key[1]}")
        features.write_route(builder, log, gml_id, uid, rec["designator"],
                             rec["loc_designator"],
                             mapping.parse_dt_wef(rec["dt_wef"]))
        remember(gml_id, rec["created_by"])
        route_uuids[key] = uid
    counts["Route"] = len(route_uuids)

    # ── 5. RouteSegment ─────────────────────────────────────────────────────
    print("\n[5] Rota segmentleri yazılıyor (uç noktalar çözümleniyor)...")
    for n, rec in enumerate(route_records, 1):
        gml_id = ids.make("RS", f"{n:06d}")
        uid = feature_uuid("EadRouteSegment", rec["mid"] or gml_id)

        seg = {
            "level": rec["level"],
            "upper_limit": rec["upper_limit"], "upper_uom": rec["upper_uom"],
            "upper_ref": rec["upper_ref"],
            "lower_limit": rec["lower_limit"], "lower_uom": rec["lower_uom"],
            "lower_ref": rec["lower_ref"],
            "route_uuid": route_uuids.get(
                (rec["designator"] or "", rec["loc_designator"] or "")),
        }
        resolved = resolver.resolve_segment(rec, gml_id)
        for side in ("start", "end"):
            uuid_value, kind, coord = resolved[side]
            seg[f"{side}_uuid"] = uuid_value
            seg[f"{side}_kind"] = kind
            seg[f"{side}_coord"] = coord

        features.write_route_segment(builder, log, gml_id, uid, seg,
                                     mapping.parse_dt_wef(rec["dt_wef"]))
        remember(gml_id, rec["created_by"])
    counts["RouteSegment"] = len(route_records)

    # ── 6. Yaz ──────────────────────────────────────────────────────────────
    builder.close()
    OUTPUT_ORIGINATORS.write_text(
        json.dumps(originators, ensure_ascii=False, indent=1), encoding="utf-8")

    size_mb = OUTPUT_XML.stat().st_size / 1024 / 1024
    print("\n" + "=" * 60)
    print(f"Cikti      : {OUTPUT_XML.name} ({size_mb:.1f} MB)")
    print(f"Originators: {OUTPUT_ORIGINATORS.name} ({len(originators)} kayit)")
    for k, v in counts.items():
        print(f"  {k:28} {v}")
    print(f"  {'TOPLAM feature':28} {builder.count}")

    print("\nUc nokta cozunurlugu:")
    total_ep = 2 * len(route_records)
    resolved = resolver.stats["dp_cozuldu"] + resolver.stats["navaid_cozuldu"] \
        + resolver.stats["ndb_cozuldu"]
    print(f"  toplam uc nokta            {total_ep}")
    print(f"  cozulen                    {resolved} ({100 * resolved / total_ep:.1f}%)")
    for k, v in sorted(resolver.stats.items()):
        print(f"    {k:26} {v}")

    summary = log.summary()
    print(f"\nerrored-features.log: {sum(summary.values())} kayit")
    for k, v in summary.items():
        print(f"  {k:38} {v}")
    log.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
