"""LT rota verisini AIXM 5.2 XML'ine dönüştüren ana script.

Girdi : ../LT Route Data Fetcher/raw-data/  (6 ham geojson + 4 *_info.json)
Çıktı : ../lt-route-data-aixm.xml
Log   : errored-features.log (her çalıştırmada sıfırlanır)

Tüm alan/enum eşlemeleri mapping.py'de, gerekçeleri DHMI_to_AIXM_Mapping.md'de.
"""

import json
import re
import sys
from datetime import datetime
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(BASE_DIR))

import mapping
from ids import IdRegistry, feature_uuid
from logger import ErrorLog, NotesFile
from sources import ats, vfr
from aixm import designated_point, navaid, route, route_segment
from aixm.writer import MessageBuilder

LT_DIR = BASE_DIR.parent
RAW_DIR = LT_DIR / "LT Route Data Fetcher" / "raw-data"
OUTPUT = LT_DIR / "lt-route-data-aixm.xml"
LOG_PATH = BASE_DIR / "errored-features.log"
NOTES_PATH = BASE_DIR / "not.txt"
OVERRIDE_PATH = BASE_DIR / "attribute-override.json"
DATA_JSON = LT_DIR / "data.json"

HEADER_COMMENT = "Generated by Ibosoft AIS - ais.ibosoft.net.tr"

_MONTHS = {"JAN": 1, "FEB": 2, "MAR": 3, "APR": 4, "MAY": 5, "JUN": 6,
           "JUL": 7, "AUG": 8, "SEP": 9, "OCT": 10, "NOV": 11, "DEC": 12}


def load_effectivity(log) -> str:
    """data.json'daki "06 AUG 2026 (AIRAC 2608)" → "2026-08-06T00:00:00Z"."""
    try:
        with open(DATA_JSON, encoding="utf-8") as f:
            raw = json.load(f).get("data_effectivity", "")
    except OSError:
        raw = ""
    m = re.match(r"\s*(\d{1,2})\s+([A-Z]{3})\s+(\d{4})", raw.upper())
    if not m:
        log.error("Message", "-", "data_effectivity", raw,
                  "yururluk_tarihi_cozulemedi")
        return datetime.now().strftime("%Y-%m-%dT00:00:00Z")
    day, mon, year = int(m.group(1)), _MONTHS[m.group(2)], int(m.group(3))
    return f"{year:04d}-{mon:02d}-{day:02d}T00:00:00Z"


def load_overrides(log) -> dict:
    with open(OVERRIDE_PATH, encoding="utf-8") as f:
        data = json.load(f)
    return {k: v for k, v in data.items() if not k.startswith("_")}


def main():
    log = ErrorLog(LOG_PATH)
    notes = NotesFile(NOTES_PATH)
    ids = IdRegistry("LT")
    overrides = load_overrides(log)
    builder = MessageBuilder("LT_MSG_ROUTE_DATA", load_effectivity(log), ids)

    counts = {}

    # ── 1. ATS noktaları ────────────────────────────────────────────────────
    dp_records, navaid_records = ats.load_points(RAW_DIR, log)

    # İsim indeksi: uç nokta çözümü için (DP designator + navaid NAME).
    dp_index, navaid_index = {}, {}

    for rec in sorted(dp_records, key=lambda r: r["designator"]):
        gml_id = ids.make("DP", rec["designator"])
        uid = feature_uuid("DesignatedPoint", rec["designator"])
        designated_point.write(builder, log, gml_id, uid, rec,
                               designator=rec["designator"],
                               point_type=rec["type"])
        _index(dp_index, rec["designator"], (uid, rec["lat"], rec["lon"]),
               log, "DesignatedPoint")
    counts["DesignatedPoint (ATS)"] = len(dp_records)

    for rec in sorted(navaid_records, key=lambda r: r["name"]):
        gml_id = ids.make("NAV", rec["designator"] or rec["name"])
        uid = feature_uuid("Navaid", f"{rec['type']}:{rec['designator']}")
        nav_name, nav_note = _name_and_note(rec["name"], log, "Navaid", gml_id)
        navaid.write(builder, log, gml_id, uid,
                     navaid_type=rec["type"], designator=rec["designator"],
                     name=nav_name, lat=rec["lat"], lon=rec["lon"],
                     annotation=nav_note)
        _index(navaid_index, rec["name"], (uid, rec["lat"], rec["lon"]),
               log, "Navaid")
        # Fix çözümü designator ile yapılır (VFR açıklamaları kodu kullanır).
        navaid_index.setdefault("#" + rec["designator"], (uid, rec["lat"], rec["lon"]))
    counts["Navaid (ATS)"] = len(navaid_records)

    # ── 2. VFR noktaları ────────────────────────────────────────────────────
    vfr_points = vfr.load_points(RAW_DIR, log)
    vfr_index = {}
    stub_navaids = {}

    for rec in vfr_points:
        gml_id = ids.make("VRP", mapping.ascii_name(rec["name"]))
        uid = feature_uuid("VfrPoint", rec["kid"])
        fixes = _resolve_fixes(rec, navaid_index, stub_navaids, log, gml_id)
        name, note_text = _name_and_note(rec["name"], log,
                                         "DesignatedPoint(VFR)", gml_id)
        designated_point.write(
            builder, log, gml_id, uid, rec,
            name=name,                              # designator BOŞ bırakılır
            point_type=overrides["vfr"]["DesignatedPoint"]["type"],
            fixes=fixes, annotation=note_text,
        )
        # Aynı isim farklı konumda olabildiği için anahtar isim+koordinat.
        vfr_index[(rec["name"], _key(rec["lon"], rec["lat"]))] = uid
    counts["DesignatedPoint (VFR)"] = len(vfr_points)

    # Kaynakta tanımlı olmayan, yalnızca VFR fix referanslarında geçen navaid'ler.
    for code, uid in sorted(stub_navaids.items()):
        gml_id = ids.make("NAV", code)
        navaid.write(
            builder, log, gml_id, uid, designator=code,
            annotation="Kaynak veride tanimli degil; VFR nokta fix "
                       "referansindan turetilmis stub kaydidir. Konum ve tip "
                       "bilgisi kaynakta bulunmadigi icin yazilmamistir.",
        )
    counts["Navaid (stub)"] = len(stub_navaids)

    # ── 3. ATS rotaları ve segmentleri ──────────────────────────────────────
    segments = ats.load_segments(RAW_DIR, log)

    route_uuids = {}
    for designator in sorted({s.get("ROUTE_DESIGNATOR", "").strip()
                              for s in segments if s.get("ROUTE_DESIGNATOR")}):
        gml_id = ids.make("RTE", designator.replace(" ", ""))
        uid = feature_uuid("Route", designator)
        route.write(builder, log, gml_id, uid, designator=designator,
                    overrides=overrides["ats"]["Route"])
        route_uuids[designator] = uid
    counts["Route (ATS)"] = len(route_uuids)

    for n, raw in enumerate(segments, 1):
        gml_id = ids.make("RS", f"{n:04d}")
        uid = feature_uuid("RouteSegment", raw["kid"])
        seg = _normalize_ats_segment(raw, gml_id, dp_index, navaid_index,
                                     route_uuids, log)
        _note_dropped(seg, "RouteSegment(ATS)", gml_id, raw, log, notes)
        route_segment.write(builder, log, gml_id, uid, seg,
                            overrides=overrides["ats"]["RouteSegment"])
    counts["RouteSegment (ATS)"] = len(segments)

    # ── 4. VFR rotaları ve segmentleri ──────────────────────────────────────
    vfr_segments = vfr.load_segments(RAW_DIR, log)

    # Kullanıcı kararı: VFR rota kimliği `hi` alanıdır (pic'teki "LTFE/SOUTH"
    # değil) — aynı adlı farklı havaalanı rotaları bilerek birleşir.
    vfr_route_uuids = {}
    for raw_name in sorted({s["hi"] for s in vfr_segments if s["hi"]}):
        gml_id = ids.make("RTE_VFR", mapping.ascii_name(raw_name))
        uid = feature_uuid("VfrRoute", raw_name)
        name, note_text = _name_and_note(raw_name, log, "Route(VFR)", gml_id)
        route.write(builder, log, gml_id, uid, name=name,
                    overrides=overrides["vfr"]["Route"], annotation=note_text)
        # Segment eşlemesi kaynaktaki özgün ad üzerinden yapılır.
        vfr_route_uuids[raw_name] = uid
    counts["Route (VFR)"] = len(vfr_route_uuids)

    for n, raw in enumerate(vfr_segments, 1):
        gml_id = ids.make("RS_VFR", f"{n:04d}")
        uid = feature_uuid("VfrSegment", raw["kid"])
        seg = _normalize_vfr_segment(raw, gml_id, vfr_index, vfr_route_uuids, log)
        _note_dropped(seg, "RouteSegment(VFR)", gml_id, raw, log, notes)
        route_segment.write(builder, log, gml_id, uid, seg,
                            overrides=overrides["vfr"]["RouteSegment"])
    counts["RouteSegment (VFR)"] = len(vfr_segments)

    # ── 5. Yaz ──────────────────────────────────────────────────────────────
    builder.write(OUTPUT, HEADER_COMMENT)

    print(f"\n{'='*60}")
    print(f"Cikti: {OUTPUT}")
    for k, v in counts.items():
        print(f"  {k:26} {v}")
    print(f"  {'TOPLAM feature':26} {sum(counts.values())}")
    summary = log.summary()
    print(f"\nerrored-features.log: {sum(summary.values())} kayit")
    for k, v in summary.items():
        print(f"  {k:34} {v}")
    print(f"\nnot.txt: {notes.count} kayitta alan dusuruldu (elle eklenmeli)")
    log.close()
    notes.close()


# ── Yardımcılar ─────────────────────────────────────────────────────────────

def _key(lon, lat):
    return (round(float(lon), 5), round(float(lat), 5))


def _name_and_note(raw_name, log, feature, ident):
    """ASCII'ye çevrilmiş ad + (değiştiyse) orijinali koruyan not döndürür.

    AIXM TextNameType ASCII-only olduğu için Türkçe karakterler çevrilir;
    kullanıcı kararı gereği orijinal yazım annotation içinde saklanır.
    """
    name = mapping.ascii_name(raw_name)
    if name == raw_name:
        return name, None
    if not mapping.is_ascii(name):
        log.error(feature, ident, "name", raw_name, "ascii_disi_karakter_kaldi")
    log.warning(feature, ident, "name", f"{raw_name} -> {name}",
                "ascii_ye_cevrildi")
    # Not, yalnızca özgün yazımı taşır — açıklama metni eklenmez.
    return name, raw_name


def _check_bearing(value, field, dropped):
    """Kerteriz 0-360 aralığında mı? Değilse alanı düşürür (boş döndürür).

    Kullanıcı kararı: bozuk kaynak değeri DÜZELTİLMEZ (gelecek ay yine bozuk
    veri gelebilir) — yalnızca hatalı ALAN düşürülür, kayıt XML'de kalır.
    Düşürülen alan not.txt'ye yazılır ki doğru değer elle eklenebilsin.
    """
    if not value:
        return value
    try:
        f = float(value)
    except ValueError:
        dropped.append(f"{field}: sayisal degil ({value}) -> alan yazilmadi")
        return ""
    if not 0 <= f <= 360:
        dropped.append(f"{field}: 0-360 araligi disinda ({value}) -> alan yazilmadi")
        return ""
    return value


def _note_dropped(seg, feature, ident, source_record, log, notes):
    """Düşürülen alanları loglar ve not.txt'ye yazar. Kayıt yine de yazılır."""
    reasons = seg.get("_dropped") or []
    if not reasons:
        return
    for r in reasons:
        log.error(feature, ident, r.split(":")[0], "-", "hatali_alan_dusuruldu")
    notes.add(feature, ident, reasons, source_record)


def _index(store, key, value, log, feature):
    if key in store:
        log.error(feature, key, "-", "-", "ayni_isim_birden_fazla_nokta")
    store[key] = value


def _resolve_fixes(rec, navaid_index, stub_navaids, log, gml_id):
    """VFR nokta açıklamasını PointReference girdilerine çevirir."""
    triples = mapping.parse_vfr_fix(rec["description"])
    if rec["description"] and not triples:
        log.warning("DesignatedPoint(VFR)", gml_id, "description",
                    rec["description"], "fix_deseni_cozulemedi")
        return []

    fixes = []
    for code, radial, distance in triples:
        entry = navaid_index.get("#" + code)
        if entry is None:
            uid = stub_navaids.get(code)
            if uid is None:
                uid = feature_uuid("NavaidStub", code)
                stub_navaids[code] = uid
                log.warning("Navaid", code, "designator", code,
                            "kaynakta_tanimsiz_navaid_stub_uretildi")
        else:
            uid = entry[0]
        fixes.append({"navaid_uuid": uid,
                      "radial": mapping.number(radial),
                      "distance": mapping.number(distance)})
    return fixes


def _resolve_endpoint(name, dp_index, navaid_index, log, gml_id, side):
    """Uç nokta ismini önce DP, sonra navaid indeksinde arar.

    Kullanıcı kararı: uzunluk kuralı kullanılmaz (5 harfli navaid adları
    nedeniyle hatalıydı); isim doğrudan aranır — çakışma yok, doğrulandı.
    """
    if not name:
        log.error("RouteSegment", gml_id, f"{side}PointName", "-",
                  "uc_nokta_adi_bos")
        return None, None
    entry = dp_index.get(name)
    if entry is not None:
        return entry, "DP"
    entry = navaid_index.get(name)
    if entry is not None:
        return entry, "NAVAID"
    log.error("RouteSegment", gml_id, f"{side}PointName", name,
              "uc_nokta_cozulemedi")
    return None, None


def _normalize_ats_segment(raw, gml_id, dp_index, navaid_index, route_uuids, log):
    seg = {
        "level": raw.get("LEVEL", "").strip(),
        "upperLimitReference": raw.get("UPPER_LIMIT_REFERENCE", "").strip(),
        "lowerLimitReference": raw.get("LOWER_LIMIT_REFERENCE", "").strip(),
        "trueTrack": mapping.number(raw.get("TRUE_TRACK", "")),
        "magneticTrack": mapping.number(raw.get("MAGNETIC_TRACK", "")),
        "reverseTrueTrack": mapping.number(raw.get("REVERSE_TRUE_TRACK", "")),
        "reverseMagneticTrack": mapping.number(raw.get("REVERSE_MAGNETIC_TRACK", "")),
        "length": mapping.number(raw.get("LENGTH", "")),
        "widthLeft": mapping.number(raw.get("WIDTH_LEFT", "")),
        "widthRight": mapping.number(raw.get("WIDTH_RIGHT", "")),
    }
    seg["upperLimit"] = mapping.vertical_limit(raw.get("UPPER_LIMIT", ""))
    seg["lowerLimit"] = mapping.vertical_limit(raw.get("LOWER_LIMIT", ""))
    seg["upperLimitUom"] = mapping.vertical_uom(seg["upperLimitReference"])
    seg["lowerLimitUom"] = mapping.vertical_uom(seg["lowerLimitReference"])

    dropped = []
    for field in ("trueTrack", "reverseTrueTrack", "magneticTrack",
                  "reverseMagneticTrack"):
        seg[field] = _check_bearing(seg[field], field, dropped)
    seg["_dropped"] = dropped

    nav_type = raw.get("NAVIGATION_TYPE", "").strip()
    if nav_type:
        mapped = mapping.NAVIGATION_TYPE.get(nav_type)
        if mapped is None:
            log.error("RouteSegment", gml_id, "NAVIGATION_TYPE", nav_type,
                      "bilinmeyen_navigation_type")
        seg["navigationType"] = mapped

    rnp = raw.get("REQUIRED_NAVIGATION_PERFORMANCE", "").strip()
    if rnp:
        mapped = mapping.NAVIGATION_SPECIFICATION.get(rnp)
        if mapped is None:
            log.error("RouteSegment", gml_id, "REQUIRED_NAVIGATION_PERFORMANCE",
                      rnp, "bilinmeyen_rnp_degeri")
        seg["navigationSpecification"] = mapped

    for side, field in (("start", "START"), ("end", "END")):
        name = raw.get(f"{field}_POINT_NAME", "").strip()
        entry, kind = _resolve_endpoint(name, dp_index, navaid_index, log,
                                        gml_id, side)
        if entry:
            seg[f"{side}PointUuid"], plat, plon = entry
            seg[f"{side}PointKind"] = kind
            seg[f"{side}Coord"] = (plat, plon)
            _check_coord(raw.get(f"{field}_POINT_COORDINATES", ""), plat, plon,
                         log, gml_id, side, name)
        else:
            coord = _parse_coord(raw.get(f"{field}_POINT_COORDINATES", ""))
            seg[f"{side}Coord"] = coord
        seg[f"{side}ReportingATC"] = raw.get(f"{field}_POINT_REPORTING_ATC", "").strip()

    designator = raw.get("ROUTE_DESIGNATOR", "").strip()
    if designator:
        seg["routeUuid"] = route_uuids.get(designator)
    else:
        log.error("RouteSegment", gml_id, "ROUTE_DESIGNATOR", "-",
                  "rota_kodu_yok")
    return seg


def _parse_coord(text):
    """"38.52389 35.22889" → (lat, lon). Kaynak enlem-boylam sırasındadır."""
    parts = (text or "").split()
    if len(parts) != 2:
        return None
    try:
        return (float(parts[0]), float(parts[1]))
    except ValueError:
        return None


def _check_coord(text, lat, lon, log, gml_id, side, name):
    coord = _parse_coord(text)
    if coord is None:
        return
    if _key(coord[1], coord[0]) != _key(lon, lat):
        log.warning("RouteSegment", gml_id, f"{side}PointCoordinates", text,
                    f"koordinat_nokta_ile_uyusmuyor({name})")


def _normalize_vfr_segment(raw, gml_id, vfr_index, route_uuids, log):
    seg = {
        "length": mapping.number(raw.get("distance", "")),
        "trueTrack": mapping.number(raw.get("calc_start", "")),
        "reverseTrueTrack": mapping.number(raw.get("calc_end", "")),
        "magneticTrack": mapping.number(raw.get("magnetic_start", "")),
        "reverseMagneticTrack": mapping.number(raw.get("magnetic_end", "")),
        "routeUuid": route_uuids.get(raw["hi"]),
    }
    dropped = []
    for field in ("trueTrack", "reverseTrueTrack", "magneticTrack",
                  "reverseMagneticTrack"):
        seg[field] = _check_bearing(seg[field], field, dropped)
    seg["_dropped"] = dropped

    for side, name_key, coord_key in (("start", "start_point", "start_coord"),
                                      ("end", "end_point", "end_coord")):
        name = raw.get(name_key, "")
        lon, lat = raw[coord_key]
        uid = vfr_index.get((name, _key(lon, lat)))
        if uid is None:
            log.error("RouteSegment(VFR)", gml_id, name_key, name,
                      "vfr_uc_nokta_cozulemedi")
        else:
            seg[f"{side}PointUuid"] = uid
            seg[f"{side}PointKind"] = "DP"
        seg[f"{side}Coord"] = (lat, lon)
    return seg


if __name__ == "__main__":
    main()
